db:
  username: ${username.value:postgres}
  password: pass
  url: postgres:5432
  hosts: localhost,127.0.0.1
  driver: PostgresDriver
  properties:
    first: 123
    second: 456
    third.value: Third
  pool:
    size: 12
    timeout: 10
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
    - size: 3
      timeout: 3

logging:
  level:
    root: info
    ru.michaelshell.spring.database.pool.ConnectionPool: info
    org.springframework.jdbc.core: trace
  file:
    name: michaelshell.log
    path: /

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    format:
      date: iso
  profiles:
    active: qa
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        batch_size: 50
        fetch.size: 50
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: validate
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 1065508579395-v8p66h0tovlv881do9lapt4uocghmm4a.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: http://localhost:8080/login/oauth2/code/google
            scope: openid,email,profile
  messages:
    basename: messages
springdoc:
  swagger-ui:
    oauth:
      client-id: 1065508579395-v8p66h0tovlv881do9lapt4uocghmm4a.apps.googleusercontent.com
      client-secret: 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
      scopes: openid,email,profile
    oauth2-redirect-url: http://localhost:8080/swagger-ui/oauth2-redirect.html