db: 
  username: ${username.value:postgres}
  password: pass
  url: postgres:5432
  hosts: localhost,127.0.0.1
  driver: PostgresDriver
  properties:
    first: 123
    second: 456
    third.value: Third
  pool:
    size: 12
    timeout: 10
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
    - size: 3
      timeout: 3

logging:
  level:
    root: warn
    ru.michaelshell.spring.database.pool.ConnectionPool: info
  file:
    name: michaelshell.log
    path: /